site_name: My Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.expand
plugins:
    - awesome-pages